version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churrasqueando-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=churrasqueando
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - MERCADOPAGO_ACCESS_TOKEN=${MERCADOPAGO_ACCESS_TOKEN}
    depends_on:
      - postgres
    networks:
      - churrasqueando-network

  nginx:
    image: nginx:alpine
    container_name: churrasqueando-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - churrasqueando-network

  postgres:
    image: postgres:15
    container_name: churrasqueando-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: churrasqueando
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - churrasqueando-network

volumes:
  postgres_data:

networks:
  churrasqueando-network:
    driver: bridge